baseurl = "https://romain.rbind.io"
relativeurls = true
languageCode = "en-us"
title = "Romain François - Consulting Datactive"
theme = "hugo-lithium-theme"
author = "Romain François"
paginate = 10
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  subtitle = "Romain François"
  brand = "<img src='/img/datactive.png' width='130'/>"
  description = "Consulting Datactive. R/C++ hero"
  disqus = "romain-rbind-io"
  highlightjs = "github"
  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"

[menu]  
  [[menu.main]]
      name = "Home"
      pre = "<i class='fa fa-home fa-fw'></i>"
      weight = 1
      identifier = "home"
      url = "/"
  [[menu.main]]
    name = "Archive"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "post"
    url = "/post/"

  [[menu.main]]
      name = "ThinkR"
      pre = "<i class='fa fa-laptop fa-fw'></i>"
      url = "http://www.thinkr.fr"

[social]
  twitter = "romain_francois"
  instagram = "romain_francois"
  github = "romain_francois"
  stackoverflow = "romain-francois"
  linkedin = "romain-francois"

